
noun = input("Enter a Noun: ")
plural_noun = input("Enter a plural noun: ")
verb_ing = input("Enter a verb ending in ing: ")
plural_noun2 = input("Enter another plural noun: ")
city = input("Enter a City: ")
plural_noun3 = input("Enter another plural noun: ")
adjective = input("Enter an adjective: ")
noun2 = input("Enter another noun: ")
num = input("Enter a number: ")
noun3 = input("Enter another noun: ")
adjective2 = input("How bout another adjective: ")
verb = input("Hit me with a verb: ")
verb2 = input("Verb again, Please: ")
plural_noun4 = input("Anotha plural noun: ")
verb_ing2 = input("One more verb ending in ing: ")
num2 = input("Another number: ")
adverb = input("Give an adverb, please: ")
noun5 = input("Noun me: ")
adjective3 = input("Last but not least, another adjective: ")

print("In 1981, the US launched the first real space " + noun + ".")
print("It was named Columbia and was piloted by two brave " + plural_noun + ".")
print("They had practiced " + verb_ing + " for two years and were expert " + plural_noun2 + ".")
print("Columbia took off from " + city + " using its powerful first-stage " + plural_noun3 + " and soared off into the " + adjective + " blue " + noun2 + ".")
print("At an altitude of " + num + " feet, it went into orbit around the " + noun3 + ".")
print("For people watching from Earth, it was a/an " + adjective2 + " sight to " + verb + "!")
print("Who could really " + verb2 + " that there were two " + plural_noun4 + " in space?")
print("It was mind " + verb_ing2 + ".")
print("After " + num2 + " orbits, the shuttle landed " + adverb + " at an Air force " + noun5 + ".")
print("It was a/an " + adjective3 + " day for the US space program.")
